# Generated by Django 3.1.7 on 2021-03-01 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('teacher_id', models.CharField(default=None, max_length=50, primary_key=True, serialize=False)),
                ('teacher_name', models.CharField(default=None, max_length=50)),
                ('email', models.CharField(default=None, max_length=50)),
            ],
        ),
    ]
