# Generated by Django 3.1.7 on 2021-03-30 07:13

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teacher', '0002_auto_20210330_1258'),
        ('student', '0002_auto_20210330_1258'),
    ]

    operations = [
        migrations.CreateModel(
            name='application_form',
            fields=[
                ('application_id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('status', models.BooleanField(default=False, max_length=3)),
                ('semester', models.IntegerField()),
                ('application_date', models.DateField(default=datetime.datetime(2021, 3, 30, 7, 13, 12, 444245, tzinfo=utc))),
            ],
        ),
        migrations.CreateModel(
            name='Exams',
            fields=[
                ('exam_id', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('exam_title', models.CharField(max_length=25)),
                ('exam_format', models.CharField(max_length=6)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('full_marks', models.IntegerField(default=100)),
                ('pass_marks', models.IntegerField(default=40)),
                ('exam_centre', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Term',
            fields=[
                ('term_id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('year', models.IntegerField(choices=[(1990, 1990), (1991, 1991), (1992, 1992), (1993, 1993), (1994, 1994), (1995, 1995), (1996, 1996), (1997, 1997), (1998, 1998), (1999, 1999), (2000, 2000), (2001, 2001), (2002, 2002), (2003, 2003), (2004, 2004), (2005, 2005), (2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021)], default=2021)),
                ('exam_name', models.CharField(max_length=25)),
                ('Start_date', models.DateField()),
                ('End_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('subject_code', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('subject_name', models.CharField(max_length=25)),
                ('teacher_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_teacher', to='teacher.teacher')),
            ],
        ),
        migrations.CreateModel(
            name='studentgrades',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marks', models.IntegerField()),
                ('passed', models.BooleanField()),
                ('exam_type', models.BooleanField()),
                ('application_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.application_form')),
                ('exam_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.exams')),
            ],
        ),
        migrations.CreateModel(
            name='selectedcourses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(choices=[(1990, 1990), (1991, 1991), (1992, 1992), (1993, 1993), (1994, 1994), (1995, 1995), (1996, 1996), (1997, 1997), (1998, 1998), (1999, 1999), (2000, 2000), (2001, 2001), (2002, 2002), (2003, 2003), (2004, 2004), (2005, 2005), (2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021)], default=2021)),
                ('semester', models.IntegerField(default=None)),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_student', to='student.student')),
                ('subject_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.subject')),
            ],
        ),
        migrations.AddField(
            model_name='exams',
            name='subject_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.subject'),
        ),
        migrations.AddField(
            model_name='exams',
            name='term',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.term'),
        ),
        migrations.AddField(
            model_name='application_form',
            name='exam',
            field=models.ManyToManyField(through='courses.studentgrades', to='courses.Exams'),
        ),
        migrations.AddField(
            model_name='application_form',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.student'),
        ),
        migrations.AddField(
            model_name='application_form',
            name='term',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.term'),
        ),
    ]
