# Generated by Django 3.1.7 on 2021-03-01 08:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('student', '0001_initial'),
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exams',
            fields=[
                ('exam_id', models.CharField(default=None, max_length=50, primary_key=True, serialize=False)),
                ('exam_title', models.CharField(default=None, max_length=50)),
                ('exam_format', models.CharField(default=None, max_length=50)),
                ('date', models.DateField(default=None)),
                ('time', models.TimeField(default=None)),
                ('room', models.CharField(default=None, max_length=50)),
                ('class_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='student.class')),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('subject_code', models.CharField(default=None, max_length=50, primary_key=True, serialize=False)),
                ('subject_name', models.CharField(default=None, max_length=50)),
                ('subject_author', models.CharField(default=None, max_length=50)),
                ('pass_marks', models.IntegerField(default=None)),
                ('final_marks', models.IntegerField(default=None)),
                ('teacher_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='subject_teacher', to='teacher.teacher')),
            ],
        ),
        migrations.CreateModel(
            name='studentgrades',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marks', models.IntegerField(default=0)),
                ('exam_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='courses.exams')),
                ('student_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='grade_student', to='student.student')),
            ],
        ),
        migrations.CreateModel(
            name='selectedcourses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(default=0)),
                ('student_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='course_student', to='student.student')),
                ('subject_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='courses.subject')),
            ],
        ),
        migrations.AddField(
            model_name='exams',
            name='subject_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='courses.subject'),
        ),
    ]
