# Generated by Django 3.1.7 on 2021-03-30 07:29

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application_form',
            name='application_date',
            field=models.DateField(default=datetime.datetime(2021, 3, 30, 7, 29, 52, 450618, tzinfo=utc)),
        ),
    ]
