# Generated by Django 3.1.7 on 2021-03-03 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exams',
            name='class_id',
        ),
        migrations.RemoveField(
            model_name='selectedcourses',
            name='year',
        ),
        migrations.AddField(
            model_name='selectedcourses',
            name='semester',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='studentgrades',
            name='semester',
            field=models.IntegerField(default=None),
        ),
    ]
