# Generated by Django 3.1.7 on 2021-03-30 09:06

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_auto_20210330_1314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application_form',
            name='application_date',
            field=models.DateField(default=datetime.datetime(2021, 3, 30, 9, 6, 45, 552878, tzinfo=utc)),
        ),
    ]
