# Generated by Django 3.1.7 on 2021-03-05 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_auto_20210303_1147'),
    ]

    operations = [
        migrations.AddField(
            model_name='exams',
            name='status',
            field=models.CharField(choices=[('Mid Term', 'Mid Term'), ('Final Term', 'Final Term')], default='Mid Term', max_length=16),
            preserve_default=False,
        ),
    ]
