# Generated by Django 3.1.7 on 2021-03-05 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_exams_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exams',
            old_name='status',
            new_name='term',
        ),
    ]
