# Generated by Django 3.1.7 on 2021-04-04 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_auto_20210404_1142'),
    ]

    operations = [
        migrations.RenameField(
            model_name='term',
            old_name='End_date',
            new_name='end_date',
        ),
        migrations.RenameField(
            model_name='term',
            old_name='Start_date',
            new_name='start_date',
        ),
    ]
