# Generated by Django 3.1.7 on 2021-03-12 06:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_auto_20210305_1308'),
    ]

    operations = [
        migrations.CreateModel(
            name='Term',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(choices=[(1990, 1990), (1991, 1991), (1992, 1992), (1993, 1993), (1994, 1994), (1995, 1995), (1996, 1996), (1997, 1997), (1998, 1998), (1999, 1999), (2000, 2000), (2001, 2001), (2002, 2002), (2003, 2003), (2004, 2004), (2005, 2005), (2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021)], default=2021)),
                ('term', models.CharField(choices=[('MID', 'Mid Term'), ('FIN', 'Final Term')], max_length=16)),
            ],
        ),
        migrations.RenameField(
            model_name='exams',
            old_name='room',
            new_name='exam_centre',
        ),
        migrations.RemoveField(
            model_name='exams',
            name='year',
        ),
        migrations.AddField(
            model_name='studentgrades',
            name='exam_type',
            field=models.TextField(choices=[('REG', 'Regular'), ('CHO', 'Choice')], default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='exams',
            name='term',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.term'),
        ),
    ]
