# Generated by Django 3.1.7 on 2021-03-12 07:08

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_student_semester'),
        ('courses', '0006_auto_20210312_1148'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='final_marks',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='pass_marks',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='subject_author',
        ),
        migrations.RemoveField(
            model_name='term',
            name='term',
        ),
        migrations.AddField(
            model_name='exams',
            name='full_marks',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='exams',
            name='pass_marks',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='studentgrades',
            name='passed',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='term',
            name='exam_name',
            field=models.CharField(default='Board Exam', max_length=25),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='exams',
            name='exam_centre',
            field=models.CharField(default=None, max_length=30),
        ),
        migrations.AlterField(
            model_name='exams',
            name='exam_format',
            field=models.CharField(default=None, max_length=6),
        ),
        migrations.AlterField(
            model_name='exams',
            name='exam_id',
            field=models.CharField(default=None, max_length=15, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='exams',
            name='exam_title',
            field=models.CharField(default=None, max_length=25),
        ),
        migrations.AlterField(
            model_name='selectedcourses',
            name='year',
            field=models.IntegerField(choices=[(1990, 1990), (1991, 1991), (1992, 1992), (1993, 1993), (1994, 1994), (1995, 1995), (1996, 1996), (1997, 1997), (1998, 1998), (1999, 1999), (2000, 2000), (2001, 2001), (2002, 2002), (2003, 2003), (2004, 2004), (2005, 2005), (2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020)], default=2021),
        ),
        migrations.AlterField(
            model_name='studentgrades',
            name='exam_type',
            field=models.CharField(choices=[('REG', 'Regular'), ('CHO', 'Choice')], max_length=10),
        ),
        migrations.AlterField(
            model_name='studentgrades',
            name='marks',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='subject',
            name='subject_code',
            field=models.CharField(default=None, max_length=12, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='subject',
            name='subject_name',
            field=models.CharField(default=None, max_length=25),
        ),
        migrations.AlterField(
            model_name='term',
            name='year',
            field=models.IntegerField(choices=[(1990, 1990), (1991, 1991), (1992, 1992), (1993, 1993), (1994, 1994), (1995, 1995), (1996, 1996), (1997, 1997), (1998, 1998), (1999, 1999), (2000, 2000), (2001, 2001), (2002, 2002), (2003, 2003), (2004, 2004), (2005, 2005), (2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020)], default=2021),
        ),
        migrations.CreateModel(
            name='exam_application',
            fields=[
                ('application_id', models.AutoField(primary_key=True, serialize=False)),
                ('exam_type', models.CharField(choices=[('REG', 'Regular'), ('CHO', 'Choice')], max_length=5)),
                ('application_date', models.DateField(default=datetime.date.today)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.exams')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.student')),
            ],
        ),
    ]
