# Generated by Django 3.1.7 on 2021-04-11 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_auto_20210407_1340'),
    ]

    operations = [
        migrations.RenameField(
            model_name='term',
            old_name='exam_name',
            new_name='term_name',
        ),
    ]
