# Generated by Django 3.1.7 on 2021-03-12 07:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0001_initial'),
        ('student', '0003_student_semester'),
        ('courses', '0007_auto_20210312_1253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exams',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='exams',
            name='exam_centre',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='exams',
            name='exam_format',
            field=models.CharField(max_length=6),
        ),
        migrations.AlterField(
            model_name='exams',
            name='exam_id',
            field=models.CharField(max_length=15, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='exams',
            name='exam_title',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='exams',
            name='full_marks',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='exams',
            name='pass_marks',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='exams',
            name='subject_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.subject'),
        ),
        migrations.AlterField(
            model_name='exams',
            name='time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='selectedcourses',
            name='student_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_student', to='student.student'),
        ),
        migrations.AlterField(
            model_name='selectedcourses',
            name='subject_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.subject'),
        ),
        migrations.AlterField(
            model_name='studentgrades',
            name='exam_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.exams'),
        ),
        migrations.AlterField(
            model_name='studentgrades',
            name='student_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grade_student', to='student.student'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='subject_code',
            field=models.CharField(max_length=12, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='subject',
            name='subject_name',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='subject',
            name='teacher_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_teacher', to='teacher.teacher'),
        ),
    ]
