# Generated by Django 3.1.7 on 2021-03-12 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_auto_20210312_1528'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam_application',
            name='status',
            field=models.CharField(choices=[('APL', 'Applied'), ('PEN', 'Pending'), ('REG', 'Registered')], default='PEN', max_length=3),
        ),
    ]
