# Generated by Django 3.1.7 on 2021-04-19 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_auto_20210419_1219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routine',
            name='day',
            field=models.IntegerField(choices=[(1, 'Sunday'), (2, 'Monday'), (3, 'Tuesday'), (4, 'Wednesday'), (5, 'Thursday'), (6, 'Friday'), (0, 'Saturday')]),
        ),
    ]
