# Generated by Django 3.1.7 on 2021-03-12 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_exam_application_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam_application',
            name='exam_type',
            field=models.CharField(choices=[('REG', 'Regular'), ('CHA', 'Chance')], max_length=5),
        ),
        migrations.AlterField(
            model_name='exam_application',
            name='semester',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='studentgrades',
            name='exam_type',
            field=models.CharField(choices=[('REG', 'Regular'), ('CHA', 'Chance')], max_length=10),
        ),
    ]
