# Generated by Django 3.1.7 on 2021-03-12 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_auto_20210312_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam_application',
            name='semester',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
