# Generated by Django 3.1.7 on 2021-04-19 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_auto_20210419_1220'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='routine',
            constraint=models.UniqueConstraint(fields=('semester', 'subject', 'day', 'period'), name='unique_classtime'),
        ),
    ]
