# Generated by Django 3.1.7 on 2021-04-19 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0012_auto_20210419_1225'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='routine',
            name='unique_classtime',
        ),
        migrations.AddConstraint(
            model_name='routine',
            constraint=models.UniqueConstraint(fields=('semester', 'day', 'period'), name='unique_classtime'),
        ),
    ]
