# Generated by Django 3.1.7 on 2021-03-14 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0013_auto_20210312_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exams',
            name='exam_id',
            field=models.CharField(max_length=25, primary_key=True, serialize=False),
        ),
    ]
