# Generated by Django 3.1.7 on 2021-03-14 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0014_auto_20210314_1101'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam_application',
            name='form_id',
            field=models.CharField(default=None, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='exam_application',
            name='status',
            field=models.CharField(choices=[('APL', 'Applied'), ('PEN', 'Pending'), ('REG', 'Registered')], default='APL', max_length=3),
        ),
    ]
