# Generated by Django 3.1.7 on 2021-03-14 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0015_auto_20210314_2359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam_application',
            name='form_id',
            field=models.CharField(default=None, max_length=20),
        ),
    ]
