# Generated by Django 3.1.7 on 2021-03-15 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0016_auto_20210315_0001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam_application',
            name='form_id',
            field=models.CharField(default=None, max_length=20, null=True),
        ),
    ]
