# Generated by Django 3.1.7 on 2021-03-15 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0017_auto_20210315_1136'),
    ]

    operations = [
        migrations.CreateModel(
            name='application_form',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_id', models.IntegerField()),
                ('application_id', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='exam_application',
            name='form_id',
        ),
    ]
