# Generated by Django 3.1.7 on 2021-03-15 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0019_auto_20210315_1208'),
    ]

    operations = [
        migrations.AddField(
            model_name='application_form',
            name='status',
            field=models.CharField(default=1, max_length=3),
            preserve_default=False,
        ),
    ]
