# Generated by Django 3.1.7 on 2021-03-15 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0020_application_form_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application_form',
            name='status',
        ),
    ]
