# Generated by Django 3.1.7 on 2021-03-18 06:31

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_auto_20210312_1256'),
        ('courses', '0021_remove_application_form_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application_form',
            old_name='form_id',
            new_name='semester',
        ),
        migrations.RemoveField(
            model_name='application_form',
            name='id',
        ),
        migrations.RemoveField(
            model_name='studentgrades',
            name='semester',
        ),
        migrations.RemoveField(
            model_name='studentgrades',
            name='student_id',
        ),
        migrations.AddField(
            model_name='application_form',
            name='application_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='application_form',
            name='exam',
            field=models.ManyToManyField(through='courses.studentgrades', to='courses.Exams'),
        ),
        migrations.AddField(
            model_name='application_form',
            name='status',
            field=models.CharField(choices=[('APL', 'Applied'), ('PEN', 'Pending'), ('REG', 'Registered')], default='APL', max_length=3),
        ),
        migrations.AddField(
            model_name='application_form',
            name='student',
            field=models.ForeignKey(default='Stu_0001', on_delete=django.db.models.deletion.CASCADE, to='student.student'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='application_form',
            name='term',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='courses.term'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentgrades',
            name='application_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='courses.application_form'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='application_form',
            name='application_id',
            field=models.CharField(max_length=30, primary_key=True, serialize=False),
        ),
        migrations.DeleteModel(
            name='exam_application',
        ),
    ]
