# Generated by Django 3.1.7 on 2021-03-21 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0023_auto_20210319_1202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application_form',
            name='status',
            field=models.BooleanField(default=False, max_length=3),
        ),
    ]
