# Generated by Django 3.1.7 on 2021-03-01 08:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('class_id', models.CharField(default=None, max_length=50, primary_key=True, serialize=False)),
                ('class_grade', models.CharField(default=None, max_length=50)),
                ('class_section', models.CharField(default=None, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_id', models.CharField(default=None, max_length=50, primary_key=True, serialize=False)),
                ('student_name', models.CharField(default=None, max_length=50)),
                ('roll', models.IntegerField(default=None)),
                ('email', models.CharField(default=None, max_length=50)),
                ('class_obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.class')),
            ],
        ),
    ]
